name: test
on: [pull_request, push]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16.2
    - run: npm install
      working-directory: backend
    - run: npm run lint
      working-directory: backend
    - run: npm run build
      working-directory: backend

  frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.16.2
    - run: npm install
      working-directory: frontend
    - run: npm run lint
      working-directory: frontend
    - run: npm run build
      working-directory: frontend
